# gomplate template generation pipeline

inputFiles:
  - .gitlab/template.yaml.tpl

outputFiles:
  - .gitlab/build-pipeline.yaml

datasources:
  runtimes:
    url: .gitlab/datasources/runtimes.yaml

  environments:
    url: .gitlab/datasources/environments.yaml

  regions:
    url: .gitlab/datasources/regions.yaml
