ARG image
FROM $image

COPY . datadog-lambda-layer-ruby
WORKDIR /datadog-lambda-layer-ruby
ENV GEM_HOME="/usr/local/bundle"
ENV PATH $GEM_HOME/bin:$GEM_HOME/gems/bin:$PATH
RUN gem install bundler:2.2.15
RUN bundle install
RUN bundle exec rubocop lib/ test/ datadog-lambda.gemspec
