ARG image
FROM $image

COPY . datadog-lambda-ruby
WORKDIR /datadog-lambda-ruby
ENV GEM_HOME="/usr/local/bundle"
ENV PATH $GEM_HOME/bin:$GEM_HOME/gems/bin:$PATH
RUN gem install bundler:1.17.2
RUN bundle install
RUN bundle exec rubocop lib/ test/ datadog-lambda.gemspec
