ARG image
FROM $image

COPY . datadog-lambda-ruby
WORKDIR /datadog-lambda-ruby
RUN apt-get update && apt-get install -y python-pip
RUN pip install awscli
RUN gem install bundler
RUN bundle install
RUN rubocop lib/ test/ datadog-lambda.gemspec
