name: update-snapshots

on:
  workflow_dispatch:

jobs:
  update-snapshots:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        runtime-param: ["3.2", "3.3", "3.4", "4.0"]

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up Node 20
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: 20

      - name: Cache Node modules
        id: cache-node-modules
        uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5.0.4
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install Serverless Framework
        run: sudo yarn global add serverless@3 --prefix /usr/local

      - name: Install dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        working-directory: integration_tests
        run: yarn install

      - name: Install Crossbuild dependencies
        run: |
          sudo apt-get update --allow-releaseinfo-change --fix-missing
          sudo apt install -y qemu-user-static binfmt-support

      - name: Update Snapshots (amd64)
        env:
          ARCH: amd64
          UPDATE_SNAPSHOTS: true
          BUILD_LAYERS: true
          DD_API_KEY: ${{ secrets.DD_API_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          RUNTIME_PARAM: ${{ matrix.runtime-param }}
        run: ./scripts/run_integration_tests.sh

      - name: Upload snapshots
        if: always()
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: snapshots-${{ matrix.runtime-param }}
          path: |
            integration_tests/snapshots/
